FROM --platform=linux/arm/v7 python:3.8-alpine

RUN apk add --no-cache \
    mesa-gl \
    glib \
    build-base

WORKDIR /app
COPY ./req.txt /app/
RUN pip install --no-cache-dir -r req.txt

COPY ./main.py /app
EXPOSE 8000

ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
